director:
  image:
    repository: 963079663571.dkr.ecr.us-east-2.amazonaws.com/xrengine-matchmaking-director
    pullPolicy: IfNotPresent

matchfunction:
  labels:
    app: xrengine-matchmaking
    component: matchfunction
  selectorLabels:
    app: xrengine-matchmaking
    component: matchfunction
  image:
    repository: 963079663571.dkr.ecr.us-east-2.amazonaws.com/xrengine-matchmaking-matchfunction
    pullPolicy: IfNotPresent

release:
  name: dev